spring.application.name=NoteIce
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

jwt-secret: ${JWT_SECRET}
access-token-expiration-hours: ${ACCESS_TOKEN_EXPIRATION_HOURS}
refresh-token-expiration-days: ${REFRESH_TOKEN_EXPIRATION_DAYS}
verification-token-expiration-minutes: ${VERIFICATION_TOKEN_EXPIRATION_MINUTES}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${VERIFICATION_EMAIL}
spring.mail.password=${EMAIL_VERIFICATION_APP_PASSWORD}
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

url.up=http://10.0.2.2:8080/