spring.application.name=NoteIce
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

jwt-secret: ${JWT_SECRET}
access-token-expiration-hours: ${ACCESS_TOKEN_EXPIRATION_HOURS}
refresh-token-expiration-hours: ${REFRESH_TOKEN_EXPIRATION_HOURS}
